# Use an official Node.js runtime as the base image
FROM node:18-alpine AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY .env ./
RUN npm ci

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a lightweight image for the production environment
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy the build artifacts from the build stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

# Set environment variables
ENV NODE_ENV=production
ENV PORT=4696

# Expose the port the app runs on
EXPOSE 4696

# Command to run the application
CMD ["node", "dist/index.js"]